#spring.zipkin.base-url=http://localhost:9411
#spring.sleuth.sampler.rate=100
server:
  port: 14999
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}

---
spring:
  application:
    name: gateway-service

---
spring:
  cloud:
    gateway:
      discovery:
        locator:
          # \u5F00\u542F\u901A\u8FC7\u670D\u52A1\u4E2D\u5FC3\u7684\u81EA\u52A8\u6839\u636E serviceId \u521B\u5EFA\u8DEF\u7531\u7684\u529F\u80FD
          enabled: true
      routes:
        - id: add_request_header_route
          uri: lb://demo-user-service
          predicates:
            - Path= /api/user/**
          filters:
            # \u622A\u65AD\u8BF7\u6C42\u8DEF\u5F84\u6570\u91CF
            - StripPrefix= 2
            - RequestTime=true